### ISSUE TITLE
Flow Data

### ISSUE THREAD

**Issue by schiebout** [nlawlor/PBMC_CITEseq#1]
Hi there,

I was wondering if the flow data in the cell proportions plot is available anywhere for comparative analysis.

Thanks in advance!

**Comment by nlawlor** [comment]
Hello,

Thank you for your interest in the data and this app. I have attached a CSV file with the cell proportions used to generate that plot. 

Best,
Nathan


[pbmc.flow.cytometry.cell.proportions.csv](https://github.com/nlawlor/PBMC_CITEseq/files/8255080/pbmc.flow.cytometry.cell.proportions.csv)

**Comment by nlawlor** [comment]
Closing this for now, please let me know if you still have questions.

Best,
Nathan
